spring:
  application:
    name: spring-batch-data
#postgres:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
     enabled: true
     path: /h2
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema : always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

